######################################################################
# Automatically generated by qmake (3.0) Sat Jan 9 17:34:51 2016
######################################################################

TEMPLATE = app
TARGET = mongolicious
INCLUDEPATH += .
QT += gui declarative widgets

CONFIG += qt debug

# Input
HEADERS += lib/*
FORMS += ui/*
SOURCES += src/*
